import {
  FigmaVariantOverlay,
  type FigmaVariantCrop,
  type FigmaVariantHotspot,
} from "@/components/figma/FigmaVariantOverlay";
import type { ServiceDetailSlug } from "@/components/services/ServiceDetailFrame";

type OverlayConfig = React.ComponentProps<typeof FigmaVariantOverlay>;

const rowHotspots = (
  items: Array<[string, string]>,
  width = 364,
  step = 93,
): FigmaVariantHotspot[] =>
  items.map(([key, label], index) => ({
    key,
    label,
    left: 0,
    top: index * step,
    width,
    height: 72,
  }));

const variant = (
  key: string,
  label: string,
  x: number,
  y: number,
  width: number,
  height: number,
): FigmaVariantCrop => ({ key, label, x, y, width, height });

const serviceInteractions: Partial<Record<ServiceDetailSlug, OverlayConfig[]>> = {
  "mobile-app-development": [
    {
      left: 129,
      top: 2481,
      width: 1181,
      height: 444,
      sprite: "/assets/interactions/mobile-features.png",
      spriteWidth: 1221,
      spriteHeight: 2652,
      initialKey: "fast",
      variants: [
        variant("fast", "Fast Performance", 20, 20, 1181, 444),
        variant("scalable", "Scalable Design", 20, 562, 1181, 444),
        variant("multi", "Multi-Platform Reach", 20, 1104, 1181, 444),
        variant("reliable", "Reliable Code", 20, 1646, 1181, 444),
        variant("friendly", "User-Friendly Product", 20, 2188, 1181, 444),
      ],
      hotspots: rowHotspots([
        ["fast", "Show Fast Performance"],
        ["scalable", "Show Scalable Design"],
        ["multi", "Show Multi-Platform Reach"],
        ["reliable", "Show Reliable Code"],
        ["friendly", "Show User-Friendly Product"],
      ]),
    },
    {
      left: 129,
      top: 3430,
      width: 381,
      height: 526,
      sprite: "/assets/interactions/mobile-service-card.png",
      spriteWidth: 823,
      spriteHeight: 566,
      initialKey: "expanded",
      variants: [
        variant("expanded", "Custom Mobile App Development", 422, 20, 381, 526),
        variant("collapsed", "Custom Mobile App Development details", 20, 20, 381, 250),
      ],
      hotspots: [
        {
          key: "collapsed",
          label: "Toggle Custom Mobile App Development details",
          left: 0,
          top: 0,
          width: 381,
          height: 526,
          toggle: true,
        },
      ],
    },
  ],
  "desktop-app-development": [
    {
      left: 128,
      top: 3379,
      width: 1184,
      height: 723,
      sprite: "/assets/interactions/desktop-features.png",
      spriteWidth: 3860,
      spriteHeight: 2455,
      initialKey: "custom",
      variants: [
        variant("custom", "Custom Application Design and Development", 20, 20, 1184, 723),
        variant("enterprise", "Enterprise Desktop Solutions", 1338, 20, 1184, 723),
        variant("cross", "Cross-Platform Desktop Development", 2656, 20, 1184, 723),
        variant("legacy", "Legacy System Modernization", 20, 866, 1184, 723),
        variant("uiux", "UI UX Design for Desktop Apps", 1338, 866, 1184, 723),
        variant("migration", "Migration Services", 2656, 866, 1184, 723),
        variant("api", "API Development and Integration", 20, 1712, 1184, 723),
        variant("testing", "Application Testing and Quality Assurance", 1338, 1712, 1184, 723),
      ],
      hotspots: rowHotspots([
        ["custom", "Show Custom Application Design and Development"],
        ["enterprise", "Show Enterprise Desktop Solutions"],
        ["cross", "Show Cross-Platform Desktop Development"],
        ["legacy", "Show Legacy System Modernization"],
        ["uiux", "Show UI UX Design for Desktop Apps"],
        ["migration", "Show Migration Services"],
        ["api", "Show API Development and Integration"],
        ["testing", "Show Application Testing and Quality Assurance"],
      ]),
    },
    {
      left: 230,
      top: 9583,
      width: 980,
      height: 65,
      sprite: "/assets/interactions/desktop-industries.png",
      spriteWidth: 1020,
      spriteHeight: 501,
      initialKey: "logistics",
      variants: [
        variant("logistics", "Logistics and Transportation", 20, 20, 980, 65),
        variant("media", "Entertainment and Media", 20, 119, 980, 65),
        variant("education", "Education", 20, 218, 980, 65),
        variant("healthcare", "Healthcare", 20, 317, 980, 65),
        variant("estate", "Real Estate", 20, 416, 980, 65),
      ],
      hotspots: [
        { key: "logistics", label: "Show Logistics and Transportation", left: 32, top: 21, width: 216, height: 23 },
        { key: "media", label: "Show Entertainment and Media", left: 337, top: 21, width: 187, height: 23 },
        { key: "education", label: "Show Education", left: 568, top: 21, width: 83, height: 23 },
        { key: "healthcare", label: "Show Healthcare", left: 695, top: 21, width: 90, height: 23 },
        { key: "estate", label: "Show Real Estate", left: 829, top: 21, width: 119, height: 23 },
      ],
    },
  ],
  "web-app-development": [
    {
      left: 230,
      top: 11695,
      width: 980,
      height: 65,
      sprite: "/assets/interactions/web-industries.png",
      spriteWidth: 1020,
      spriteHeight: 648,
      initialKey: "commerce",
      variants: [
        variant("commerce", "E-Commerce", 20, 20, 980, 65),
        variant("healthcare", "Healthcare", 20, 110, 980, 65),
        variant("education", "Education", 20, 200, 980, 65),
        variant("finance", "Finance", 20, 290, 980, 65),
        variant("estate", "Real Estate", 20, 380, 980, 65),
        variant("travel", "Travel and Hospitality", 20, 470, 980, 65),
        variant("all", "All Industries", 20, 560, 980, 65),
      ],
      hotspots: [
        { key: "commerce", label: "Show E-Commerce", left: 32, top: 21, width: 119, height: 23 },
        { key: "healthcare", label: "Show Healthcare", left: 211.67, top: 21, width: 90, height: 23 },
        { key: "education", label: "Show Education", left: 330.33, top: 21, width: 83, height: 23 },
        { key: "finance", label: "Show Finance", left: 442, top: 21, width: 64, height: 23 },
        { key: "estate", label: "Show Real Estate", left: 534.67, top: 21, width: 90, height: 23 },
        { key: "travel", label: "Show Travel and Hospitality", left: 653.33, top: 21, width: 158, height: 23 },
        { key: "all", label: "Show All Industries", left: 840, top: 21, width: 108, height: 23 },
      ],
    },
  ],
  "ai-ml-development": [
    {
      left: 129,
      top: 2650,
      width: 1181,
      height: 491,
      sprite: "/assets/interactions/ai-features.png",
      spriteWidth: 3757,
      spriteHeight: 1038,
      initialKey: "automated",
      variants: [
        variant("automated", "Automated Daily Tasks", 20, 20, 1181, 444),
        variant("insights", "Clear Data Insights", 1288, 20, 1181, 491),
        variant("decisions", "Quick Decisions", 2556, 20, 1181, 444),
        variant("fit", "Perfect Fit", 20, 574, 1181, 444),
        variant("resources", "Efficient Resource Distribution", 1288, 574, 1181, 444),
      ],
      hotspots: rowHotspots([
        ["automated", "Show Automated Daily Tasks"],
        ["insights", "Show Clear Data Insights"],
        ["decisions", "Show Quick Decisions"],
        ["fit", "Show Perfect Fit"],
        ["resources", "Show Efficient Resource Distribution"],
      ]),
    },
  ],
  "web-3-development": [
    {
      left: 128,
      top: 3747,
      width: 1184,
      height: 710,
      sprite: "/assets/interactions/web3-features.png",
      spriteWidth: 2463,
      spriteHeight: 3231,
      initialKey: "internet",
      variants: [
        variant("internet", "Decentralized Internet", 20, 20, 1184, 710),
        variant("contracts", "Smart Contracts", 1259, 20, 1184, 710),
        variant("blockchain-app", "Blockchain Application Development", 20, 847, 1184, 710),
        variant("dapp", "Decentralized App Development", 1259, 847, 1184, 710),
        variant("consulting", "Web 3.0 Consulting Services", 20, 1674, 1184, 710),
        variant("blockchain-web", "Blockchain Web Development", 1259, 1674, 1184, 710),
        variant("crypto", "Cryptocurrency Development", 20, 2501, 1184, 710),
      ],
      hotspots: rowHotspots([
        ["internet", "Show Decentralized Internet"],
        ["contracts", "Show Smart Contracts"],
        ["blockchain-app", "Show Blockchain Application Development"],
        ["dapp", "Show Decentralized App Development"],
        ["consulting", "Show Web 3.0 Consulting Services"],
        ["blockchain-web", "Show Blockchain Web Development"],
        ["crypto", "Show Cryptocurrency Development"],
      ]),
    },
  ],
  "ui-ux-design": [
    {
      left: 129,
      top: 2432,
      width: 1181,
      height: 444,
      sprite: "/assets/interactions/uiux-features.png",
      spriteWidth: 3757,
      spriteHeight: 1043,
      initialKey: "brand",
      variants: [
        variant("brand", "Improved Brand Image", 20, 20, 1181, 444),
        variant("navigation", "Easier Navigation", 1288, 0, 1181, 444),
        variant("sales", "Increased Sales", 2556, 20, 1181, 444),
        variant("bounce", "Fewer Bounce Rates", 20, 579, 1181, 444),
        variant("engagement", "Better User Engagement", 1288, 579, 1181, 444),
      ],
      hotspots: rowHotspots([
        ["brand", "Show Improved Brand Image"],
        ["navigation", "Show Easier Navigation"],
        ["sales", "Show Increased Sales"],
        ["bounce", "Show Fewer Bounce Rates"],
        ["engagement", "Show Better User Engagement"],
      ]),
    },
  ],
  "blockchain-development": [
    {
      left: 128,
      top: 2839,
      width: 1184,
      height: 537,
      sprite: "/assets/interactions/blockchain-features.png",
      spriteWidth: 3760,
      spriteHeight: 1207,
      initialKey: "contracts",
      variants: [
        variant("contracts", "Custom Smart Contracts", 20, 20, 1184, 537),
        variant("access", "Decentralized Access Control for DApps", 1288, 20, 1184, 537),
        variant("tokens", "Custom Token Creation", 2556, 20, 1184, 537),
        variant("compliance", "Compliance Support", 20, 650, 1184, 537),
        variant("scalable", "Scalable Solutions", 1288, 650, 1184, 537),
        variant("setup", "Faster Swift Setup", 2556, 650, 1184, 537),
      ],
      hotspots: rowHotspots([
        ["contracts", "Show Custom Smart Contracts"],
        ["access", "Show Decentralized Access Control for DApps"],
        ["tokens", "Show Custom Token Creation"],
        ["compliance", "Show Compliance Support"],
        ["scalable", "Show Scalable Solutions"],
        ["setup", "Show Faster Swift Setup"],
      ]),
    },
  ],
  "game-development": [
    {
      left: 128,
      top: 2564,
      width: 1184,
      height: 630,
      sprite: "/assets/interactions/game-features.png",
      spriteWidth: 2468,
      spriteHeight: 2851,
      initialKey: "mechanics",
      variants: [
        variant("mechanics", "Custom Game Mechanics", 20, 20, 1184, 630),
        variant("characters", "Interactive Characters", 1264, 20, 1184, 630),
        variant("graphics", "Polished Graphics", 20, 747, 1184, 630),
        variant("animations", "Fluid Animations", 1264, 747, 1184, 630),
        variant("code", "Error-Free Code", 20, 1474, 1184, 630),
        variant("systems", "Easy-to-Use Game Systems", 1264, 1474, 1184, 630),
        variant("testing", "Thorough Testing", 20, 2201, 1184, 630),
      ],
      hotspots: rowHotspots([
        ["mechanics", "Show Custom Game Mechanics"],
        ["characters", "Show Interactive Characters"],
        ["graphics", "Show Polished Graphics"],
        ["animations", "Show Fluid Animations"],
        ["code", "Show Error-Free Code"],
        ["systems", "Show Easy-to-Use Game Systems"],
        ["testing", "Show Thorough Testing"],
      ]),
    },
  ],
  "product-strategy-consulting": [
    {
      left: 128,
      top: 2527,
      width: 1184,
      height: 595,
      sprite: "/assets/interactions/product-strategy-features.png",
      spriteWidth: 2498,
      spriteHeight: 2061,
      initialKey: "vision",
      variants: [
        variant("vision", "Clarity in Your Product Vision", 20, 20, 1184, 595),
        variant("market", "Market Validation", 1294, 20, 1184, 595),
        variant("decisions", "Strategic Decision-Making", 20, 733, 1184, 595),
        variant("roi", "Increased ROI", 1294, 733, 1184, 595),
        variant("risk", "Minimized Financial Risk", 20, 1446, 1184, 595),
        variant("features", "Prioritized Features", 1294, 1446, 1184, 595),
      ],
      hotspots: rowHotspots([
        ["vision", "Show Clarity in Your Product Vision"],
        ["market", "Show Market Validation"],
        ["decisions", "Show Strategic Decision-Making"],
        ["roi", "Show Increased ROI"],
        ["risk", "Show Minimized Financial Risk"],
        ["features", "Show Prioritized Features"],
      ]),
    },
  ],
  "staff-augmentation": [
    {
      left: 128,
      top: 4388,
      width: 1184,
      height: 577,
      sprite: "/assets/interactions/staff-features.png",
      spriteWidth: 2498,
      spriteHeight: 1989,
      initialKey: "full-time",
      variants: [
        variant("full-time", "Full-Time IT Staff Augmentation", 20, 20, 1184, 577),
        variant("project", "Project-Based IT Staff Augmentation", 1294, 20, 1184, 577),
        variant("temporary", "Temporary IT Staffing", 20, 706, 1184, 577),
        variant("specialized", "Specialized Skill Augmentation", 1294, 706, 1184, 577),
        variant("remote", "Remote IT Staffing", 20, 1392, 1184, 577),
        variant("consultant", "Consultant Augmentation", 1294, 1392, 1184, 577),
      ],
      hotspots: rowHotspots([
        ["full-time", "Show Full-Time IT Staff Augmentation"],
        ["project", "Show Project-Based IT Staff Augmentation"],
        ["temporary", "Show Temporary IT Staffing"],
        ["specialized", "Show Specialized Skill Augmentation"],
        ["remote", "Show Remote IT Staffing"],
        ["consultant", "Show Consultant Augmentation"],
      ]),
    },
  ],
  investment: [
    {
      left: 128,
      top: 2755,
      width: 1184,
      height: 575,
      sprite: "/assets/interactions/investment-features.png",
      spriteWidth: 2536,
      spriteHeight: 2015,
      initialKey: "resources",
      variants: [
        variant("resources", "40 Percent Dedicated Development Resources", 20, 20, 1184, 575),
        variant("launch", "We Help You Launch Faster", 1332, 20, 1184, 575),
        variant("equity", "Equity-Based Partnership for Long-Term Growth", 20, 720, 1184, 575),
        variant("software", "Custom Software Solutions", 1332, 720, 1184, 575),
        variant("guidance", "Expert Guidance from Day One", 20, 1420, 1184, 575),
        variant("record", "Proven Record of Startup Success", 1332, 1420, 1184, 575),
      ],
      hotspots: rowHotspots([
        ["resources", "Show Dedicated Development Resources"],
        ["launch", "Show We Help You Launch Faster"],
        ["equity", "Show Equity-Based Partnership"],
        ["software", "Show Custom Software Solutions"],
        ["guidance", "Show Expert Guidance from Day One"],
        ["record", "Show Proven Record of Startup Success"],
      ]),
    },
  ],
};

export function ServicePrototypeInteractions({ slug }: { slug: ServiceDetailSlug }) {
  return (
    <>
      {(serviceInteractions[slug] ?? []).map((config, index) => (
        <FigmaVariantOverlay key={`${slug}-${index}`} {...config} />
      ))}
    </>
  );
}
